# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1874f8756daefff1011bdd38570757d8280185a6bd54174866197d567f87634b5d976930ae050fdef42d8dca799ee40d7e193f4792b63687f38559c689deb29c

test:
  secret_key_base: a844b38e98ce4d014ec8b234fb071c916e57822e00a821f1323614b99b4c38775a2b3f6feec38c588a6238db86fa28c5368800413d8ebb4911da4bce6f7a1847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
